server:
  port: 8222

spring:
  application:
    name: gateway-api

#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#
#      routes:
#        - id: albums
#          uri: http://localhost:8070
#          predicates:
#            - Path=/api/v1/albums/**
#
#        - id: songs
#          uri: http://localhost:8090
#          predicates:
#            - Path=/api/v1/songs/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health , refresh , info"
  tracing:
    sampling:
      probability: 1.0
