eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



server:
  port: 0

spring:
  application:
    name: song-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/songs
    username: "postgres"
    password: "0000"
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: "health , refresh , info"
  tracing:
    sampling:
      probability: 1.0
application:
  param:
    b: 5



