spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ADIL-Ayoub/album-song-config-repo

#      server:
#        native:
#          search-locations: classpath:/configurations

server:
  port: 8888

application:
  param:
    a: 29

